import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/api";

export default function Home() {
  const { data: session } = useSession();
  const { data: project } = trpc.healthcheck.useQuery()
  return (
    <>
      <Head>
        <title>Codecollab</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-center justify-center bg-gray-900 text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-bold">Welcome to CodeCollab</h1>
          <p className="max-w-2xl text-center text-lg">
            This is a site where you can collaborate on programming projects in
            real-time. Supported languages include JavaScript, TypeScript,
            Python, Java, C++, and C#.
          </p>
          {session ? (
            <Link href={session ? "/new/project" : "/auth/login"}>
              <div className="mt-6 rounded-md bg-blue-600 px-5 py-3 text-lg font-semibold text-white transition hover:bg-blue-700">
                Create New Project
              </div>
            </Link>
          ) : (
            <div
              onClick={() => void signIn()}
              className="mt-6 rounded-md bg-blue-600 px-5 py-3 text-lg font-semibold text-white transition hover:bg-blue-700"
            >
              Login
            </div>
          )}
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
